language: swift

stages:
  - name: CocoapodsLint
  - name: CarthageBuild
  - name: Test
  - name: deploy
    if: branch = master

jobs:
  include:

    - &pod
      stage: CocoapodsLint
      install: gem install cocoapods -v '~> 1.9.3'
      script: pod lib lint --allow-warnings --fail-fast
      osx_image: xcode11.6
    # - <<: *pod
    #   osx_image: xcode11.6

    - &carthage
      stage: CarthageBuild
      script: carthage build --no-skip-current
      osx_image: xcode11.6
      name: Xcode 11.6
    # - <<: *carthage
    #   osx_image: xcode11.6
    #   name: Xcode 11.6

    - &test
      stage: Test
      name: iOS 13.3 / Xcode 11.6
      xcode_workspace: Example/TaggerKit.xcworkspace
      xcode_scheme: TaggerKit-Example
      osx_image: xcode11.6
      xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11
    # - <<: *test
    #   name: iOS 13.3 / Xcode 11
    #   osx_image: xcode11.3
    #   xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11

    - &deploy
      stage: Deploy
      name: '`pod trunk push`'
      install: gem install cocoapods -v '~> 1.9.3'
      before_script: |
        mv .github/TaggerKit.podspec .
        sed -i '' "s/s.version = '0.0.1'/s.version = '$TRAVIS_TAG'/g" TaggerKit.podspec
      script: |
        set -exo pipefail
        pod trunk push --verbose --allow-warnings | tee pod.log | ruby -e 'ARGF.each{ print "." }'
      after_failure: cat pod.log | grep error
